package com.online_values;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author manis
 */
public class Export_OnlineData2 {

    String filepath;

    // Choose File
    void chooseFile() {
        // Get the path to the user's "Documents" folder
        String userHome = System.getProperty("user.home");
        File documentsFolder = new File(userHome, "Documents");

        // Create the "EnDoc" folder if it does not exist
        File enDocFolder = new File(documentsFolder, "EnDoc/EnDoc_OnlineData");
        if (!enDocFolder.exists()) {
            enDocFolder.mkdirs();
        }

        // Opening JFileChooser
        JFileChooser selectFile = new JFileChooser(enDocFolder);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
        selectFile.setFileFilter(filter);
        selectFile.setDialogTitle("Save Online Data");

        int response = selectFile.showSaveDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            File file = selectFile.getSelectedFile();
            filepath = file.getAbsolutePath();
            if (!filepath.toLowerCase().endsWith(".csv")) {
                filepath += ".csv";
            }
        } else if (response == JFileChooser.CANCEL_OPTION) {
            filepath = "NoFile";
        }
    }

    public void save_OnlineData(JTable table_OD, JLabel Date, JLabel Time, JTextArea LUT, JTextField CAL_ID, JTextField CVN, JTextField VIN, JLabel Data_Frequency, JLabel LUT_SUM, JLabel FW_version, Boolean isADC) throws IOException {
        if (filepath == null) {
            chooseFile();
            save_OnlineData(table_OD, Date, Time, LUT, CAL_ID, CVN, VIN, Data_Frequency, LUT_SUM, FW_version, isADC);
        } else if (filepath.equals("NoFile")) {
            JOptionPane.showMessageDialog(null, "Operation was cancelled!");
        } else {
            TableModel save_model = (DefaultTableModel) table_OD.getModel();
            FileWriter writer = new FileWriter(filepath);

            // Adding Columns
            try (BufferedWriter bw = new BufferedWriter(writer)) {
                String LUTName = LUT.getText();
                String CAL_IDName = CAL_ID.getText();
                String CVNName = CVN.getText();
                String VINName = VIN.getText();
                String FW_version_data = FW_version.getText();

                bw.write("\n");
                bw.write("File Version = 1.1" + ",");
                bw.write("\n");
                bw.write("Date & Time: " + Date.getText() + " " + Time.getText() + ",");
                bw.write("\n");
                bw.write("Generated by EnDoc" + ",");
                bw.write("\n");
                bw.write("Firmware Version = " + FW_version_data + ",");
                bw.write("\n");
                bw.write("Data Measure Rate: " + Data_Frequency.getText() + ",");
                bw.write("\n");
                bw.write("\n");
                bw.write("LUT: " + LUTName + ",");
                bw.write("\n");
                bw.write("LUT SUM: " + LUT_SUM.getText() + ",");
                bw.write("\n");
                bw.write("CAL ID: " + CAL_IDName + ",");
                bw.write("\n");
                bw.write("CVN: " + CVNName + ",");
                bw.write("\n");
                bw.write("VIN: " + VINName + ",");
                bw.write("\n");

                bw.write("\n");
                bw.write("\n");
                bw.write("\n");
                bw.write("\n");

                if (isADC) {
                    bw.write("Battery[V]" + ",");
                    bw.write("TPS [%]" + ",");
                    bw.write("ERPM" + ",");
                    bw.write("EOT [°C]" + ",");
                    bw.write("DOI [μs]" + ",");
                    bw.write("Inj. per Sec" + ",");
                    bw.write("VS [Km/Hr]" + ",");
                    bw.write("Sol. Pr [kPa]" + ",");
                    bw.write("EGR Set [%]" + ",");
                    bw.write("Actual EGR [%]" + ",");
                    bw.write("ΔP mBar" + ",");
                    bw.write("EGT 1 [°C]" + ",");
                    bw.write("EGT 2 [°C]" + ",");
                    bw.write("Cons. Timer [min]" + ",");
                    bw.write("DTC Code" + ",");
                    bw.write("DTC Code 2" + ",");
                    bw.write("DTC Code 3" + ",");
                    bw.write("EOT [ADC]" + ",");
                    bw.write("EGR [ADC]" + ",");
                    bw.write("Sol. Pr. [ADC]" + ",");
                    bw.write("ΔP [ADC]" + ",");
                    bw.write("ΔP SUM / 10" + ",");
                    bw.write("ΔP Count" + ",");
                    bw.write("TPS [ADC]" + ",");
                           
                } else {
                    for (int i = 0; i < save_model.getColumnCount(); i++) {
                        bw.write(save_model.getColumnName(i) + ",");
                    }
                }

                bw.write("\n");

                for (int i = 0; i < save_model.getRowCount(); i++) {
                    for (int j = 0; j < save_model.getColumnCount(); j++) {
                        bw.write(save_model.getValueAt(i, j) + ",");
                    }
                    bw.write("\n");
                }

                JOptionPane.showMessageDialog(null, "Data Saved Successfully!");
            }
        }
    }
}
