package com.online_values;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author manis
 */
public class Export_OnlineData {

    String filepath;
    //Choose File

    void chooseFile() {

        JFileChooser selectFile = new JFileChooser();
        // Set the file chooser to show existing files in the directory

        FileNameExtensionFilter filter = new FileNameExtensionFilter("csv file", ".csv");
        selectFile.setFileFilter(filter);
        int response = selectFile.showSaveDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            File fileName = new File(selectFile.getSelectedFile().getName());
            filepath = selectFile.getSelectedFile().getPath() + ".csv";
        } else if (response == JFileChooser.CANCEL_OPTION) {
            filepath = "NoFile";
        }
    }

    public void save_OnlineData(JTable table_OD, JLabel Date, JLabel Time, JTextArea LUT, JTextField CAL_ID, JTextField CVN, JTextField VIN, JLabel Data_Frequency, JLabel LUT_SUM) throws IOException {
        if (filepath == null) {
            chooseFile();
            save_OnlineData(table_OD, Date, Time, LUT, CAL_ID, CVN, VIN, Data_Frequency, LUT_SUM);
        } else if (filepath.equals("NoFile")) {
            JOptionPane.showMessageDialog(null, "Operation was cancelled!");
        } else {
            TableModel save_model = (DefaultTableModel) table_OD.getModel();
            FileWriter writer = new FileWriter(filepath);

            //Adding Columns
            try (BufferedWriter bw = new BufferedWriter(writer)) {

                String LUTName = LUT.getText();
                String CAL_IDName = CAL_ID.getText();
                String CVNName = CVN.getText();
                String VINName = VIN.getText();

                bw.write("\n");
                bw.write("File Version = 1.1" + ",");
                bw.write("\n");
                bw.write("Date & Time: " + Date.getText() + " " + Time.getText() + ",");
                bw.write("\n");
                bw.write("Generated by EnDoc" + ",");
                bw.write("\n");
                bw.write("Data Measure Rate: " + Data_Frequency.getText() + ",");
                bw.write("\n");
                bw.write("\n");
                bw.write("LUT: " + LUTName + ",");
                bw.write("\n");
                bw.write("LUT SUM: " + LUT_SUM.getText() + ",");
                bw.write("\n");
                bw.write("CAL ID: " + CAL_IDName + ",");
                bw.write("\n");
                bw.write("CVN: " + CVNName + ",");
                bw.write("\n");
                bw.write("VIN: " + VINName + ",");
                bw.write("\n");

                bw.write("\n");
                bw.write("\n");
                bw.write("\n");
                bw.write("\n");

                for (int i = 0; i < save_model.getColumnCount(); i++) {
                    bw.write(save_model.getColumnName(i) + ",");
                }
                bw.write("\n");

                for (int i = 0; i < save_model.getRowCount(); i++) {
                    for (int j = 0; j < save_model.getColumnCount(); j++) {
                        bw.write(save_model.getValueAt(i, j) + ",");
                    }
                    bw.write("\n");
                }

                JOptionPane.showMessageDialog(null, "Data Saved Successfully!");
            }
        }

    }
}
